flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- http-api-data-0.3.5
- natural-transformation-0.4
- parsec-numbers-0.1.0
- servant-0.10
- servant-server-0.10
- haskelzinc-0.3.0.9
- parsec3-1.0.1.8
resolver: lts-7.20
