flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:GRACeFUL-project/haskelzinc.git
    commit: 443e159b8aa1be798a67e26416c0c50b4729e194
  extra-dep: true
extra-deps:
- aeson-1.1.0.0
- http-api-data-0.3.5
- natural-transformation-0.4
- parsec-numbers-0.1.0
- servant-0.10
- servant-server-0.10
- parsec3-1.0.1.8
resolver: lts-8.17
