flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/GRACeFUL-project/haskelzinc.git
    commit: 0aa2d5900ccfd21c2c0310760abde0c586240217
  extra-dep: true
extra-deps:
- aeson-1.1.0.0
- haskelzinc-0.3.0.9
- hint-0.7.0
- http-api-data-0.3.5
- parsec-numbers-0.1.0
- parsec3-1.0.1.8
- servant-0.10
- servant-server-0.10
- parsec3-1.0.1.8
resolver: lts-8.17

# Build inside Docker container
#docker:
#  enable: true

# Generate Docker images
#image:
#  container:
#    base: 'eugraceful/stack-run'
#    name: 'eugraceful/grace'
